// Generated by scripts/generate-keyboard-typo-dictionary-swift.mjs.
// Do not edit directly. The source selection data is CC BY-SA 3.0; see
// data/keyboard-typo-dictionary.md and the keyboard-typo NOTICE files.

import KanaKanjiConverterModule

let keyboardTypoDictionaryEntryCount = 96

func makeKeyboardTypoDictionaryEntries() -> [DicdataElement] {
    [
        DicdataElement(
            word: "しました",
            ruby: "シマスタ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -6.00,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ご確認",
            ruby: "ゴカクニ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -6.01,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "である",
            ruby: "デアアル",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.00,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "であった",
            ruby: "デアアッタ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.01,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "であり",
            ruby: "デアアリ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.02,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "なかった",
            ruby: "ナッカタ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.03,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "きっかけ",
            ruby: "キカッケ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.04,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ところ",
            ruby: "コトロ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.05,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ただし",
            ruby: "ダタシ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.06,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "られて",
            ruby: "ラレレテ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.07,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "られた",
            ruby: "ラレレタ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.08,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "かかわら",
            ruby: "カカラワ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.09,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "あなた",
            ruby: "アタナ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.10,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "およそ",
            ruby: "オソヨ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.11,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "いずれ",
            ruby: "イスレ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.12,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "さまざまな",
            ruby: "ザマザマナ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.13,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "すべて",
            ruby: "ズベテ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.14,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "すれば",
            ruby: "スレハ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.15,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "できず",
            ruby: "デキス",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.16,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "なければ",
            ruby: "ナケケレバ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.17,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "できる",
            ruby: "デキキル",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.18,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "しかし",
            ruby: "シシカシ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.19,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "あるいは",
            ruby: "アルイイハ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.20,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "において",
            ruby: "ニオイイテ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.21,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "そのまま",
            ruby: "ソノノママ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.22,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "なかった",
            ruby: "ナカカッタ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.23,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ファッション",
            ruby: "ファショn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.24,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ショッピング",
            ruby: "ショピング",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.25,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ヨーロッパ",
            ruby: "ヨ-ロパ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.26,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "フィンランド",
            ruby: "フィランド",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.27,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "グリーンランド",
            ruby: "グリ-ランド",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.28,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "エンディング",
            ruby: "エンディグ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.29,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "エンディング",
            ruby: "エンディンググ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.30,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "オープニング",
            ruby: "オ-プニンググ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.31,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ライセンス",
            ruby: "ラインセンス",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.32,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "キャラクター",
            ruby: "キャラクラ-",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.33,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "アニミズム",
            ruby: "アミニズム",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.34,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "グアテマラ",
            ruby: "グアマテラ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.35,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "スタッフ",
            ruby: "スッタフ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -8.36,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "そんな",
            ruby: "ソンア",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.00,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "チャンネル",
            ruby: "チャンエル",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.01,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "こんにちは",
            ruby: "コンイチハ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.02,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "どんな",
            ruby: "ドンア",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.03,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "とんねるず",
            ruby: "トンエルズ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.04,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "いろんな",
            ruby: "イロンア",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.05,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "あんな",
            ruby: "アンア",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.06,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "平和観音寺",
            ruby: "ヘイワカンオンジ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.07,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "みんな",
            ruby: "ミンア",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.08,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "おんな",
            ruby: "オンア",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.09,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "新橋",
            ruby: "シmバシ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.10,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "難波",
            ruby: "ナmバ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.11,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "散歩",
            ruby: "サmポ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.12,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "新聞",
            ruby: "シmブn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.13,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "天ぷら",
            ruby: "テmプラ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.14,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "乾杯",
            ruby: "カmパイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.15,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "先輩",
            ruby: "セmパイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.16,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "鉛筆",
            ruby: "エmピツ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.17,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "心配",
            ruby: "シmパイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.18,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "完璧",
            ruby: "カmペキ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.19,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中央",
            ruby: "チュオウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.20,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中原",
            ruby: "チュゲn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.21,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "球場",
            ruby: "キュジョウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.22,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "流星",
            ruby: "リュセイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.23,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "周年",
            ruby: "シュネn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.24,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中継",
            ruby: "チュケイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.25,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中高",
            ruby: "チュコウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.26,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中心",
            ruby: "チュシn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.27,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "きゅうり",
            ruby: "キュリ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.28,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中国",
            ruby: "チュゴク",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.29,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "駐車場",
            ruby: "チュシャジョウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.30,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "注意",
            ruby: "チュイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.31,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "宇宙船",
            ruby: "ウチュセn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.32,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "休憩",
            ruby: "キュケイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.33,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "救急",
            ruby: "キュキュウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.34,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "休日",
            ruby: "キュジツ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.35,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "給料",
            ruby: "キュリョウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.36,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "休息",
            ruby: "キュソク",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.37,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "九州",
            ruby: "キュシュウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.38,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "救助",
            ruby: "キュジョ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.39,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "週末",
            ruby: "シュマツ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.40,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "収入",
            ruby: "シュニュウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.41,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "留学",
            ruby: "リュガク",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.42,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "流行",
            ruby: "リュコウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.43,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "流通",
            ruby: "リュツウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.44,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入学",
            ruby: "ニュガク",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.45,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入院",
            ruby: "ニュイn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.46,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入力",
            ruby: "ニュリョク",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.47,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "連用形",
            ruby: "レニョウケイ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.48,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "日本郵便",
            ruby: "ニホニュウビn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.49,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用",
            ruby: "セニョウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.50,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "金曜日",
            ruby: "キニョウビ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.51,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "全容",
            ruby: "ゼニョウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.52,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "転用",
            ruby: "テニョウ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.53,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用品",
            ruby: "セニョウヒn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.54,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用車",
            ruby: "セニョウシャ",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.55,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用線",
            ruby: "セニョウセn",
            cid: CIDData.固有名詞.cid,
            mid: MIDData.一般.mid,
            value: -10.56,
            metadata: .isKeyboardTypoCorrection
        ),
    ]
}

func makeConversionDictionaryEntries(
    userEntries: [DicdataElement],
    experimentalTypoCorrectionEnabled: Bool
) -> [DicdataElement] {
    guard experimentalTypoCorrectionEnabled else {
        return userEntries
    }
    return userEntries + makeKeyboardTypoDictionaryEntries()
}

private func keyboardTypoDictionaryEntryKey(ruby: String, word: String) -> String {
    ruby + "\u{0}" + word
}

private let keyboardTypoDictionaryEntryKeys = Set(
    makeKeyboardTypoDictionaryEntries().map {
        keyboardTypoDictionaryEntryKey(ruby: $0.ruby, word: $0.word)
    }
)

func disableLearningForKeyboardTypoDictionaryCandidates(
    _ candidates: [Candidate],
    experimentalTypoCorrectionEnabled: Bool
) -> [Candidate] {
    guard experimentalTypoCorrectionEnabled else {
        return candidates
    }
    return candidates.map { source in
        var candidate = source
        if candidate.data.contains(where: {
            keyboardTypoDictionaryEntryKeys.contains(
                keyboardTypoDictionaryEntryKey(ruby: $0.ruby, word: $0.word)
            )
        }) {
            candidate.isLearningTarget = false
        }
        return candidate
    }
}
