// Generated by scripts/generate-keyboard-typo-dictionary-swift.mjs.
// Do not edit directly. The source selection data is CC BY-SA 3.0; see
// data/keyboard-typo-dictionary.md and the keyboard-typo NOTICE files.

import KanaKanjiConverterModule

let keyboardTypoDictionarySelectionCount = 92
let keyboardTypoDictionaryEntryCount = 104

func makeKeyboardTypoDictionaryEntries() -> [DicdataElement] {
    [
        DicdataElement(
            word: "しました",
            ruby: "シマスタ",
            lcid: 610,
            rcid: 435,
            mid: 17,
            value: -8.4169,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ご確認",
            ruby: "ゴカクニ",
            lcid: 560,
            rcid: 1283,
            mid: 17,
            value: -11.0794,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "である",
            ruby: "デアアル",
            lcid: 458,
            rcid: 403,
            mid: 17,
            value: -8.0747,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "であった",
            ruby: "デアアッタ",
            lcid: 458,
            rcid: 435,
            mid: 17,
            value: -9.3402,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "であり",
            ruby: "デアアリ",
            lcid: 458,
            rcid: 409,
            mid: 17,
            value: -9.2274,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "なかった",
            ruby: "ナッカタ",
            lcid: 34,
            rcid: 435,
            mid: 17,
            value: -9.3988,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "きっかけ",
            ruby: "キカッケ",
            lcid: 1285,
            rcid: 1285,
            mid: 282,
            value: -9.7538,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ところ",
            ruby: "コトロ",
            lcid: 1313,
            rcid: 1313,
            mid: 282,
            value: -6.1437,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ただし",
            ruby: "ダタシ",
            lcid: 555,
            rcid: 555,
            mid: 468,
            value: -7.1279,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "られて",
            ruby: "ラレレテ",
            lcid: 876,
            rcid: 307,
            mid: 17,
            value: -9.2370,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "られた",
            ruby: "ラレレタ",
            lcid: 876,
            rcid: 435,
            mid: 17,
            value: -9.3755,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "かかわら",
            ruby: "カカラワ",
            lcid: 780,
            rcid: 780,
            mid: 268,
            value: -9.0399,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "あなた",
            ruby: "アタナ",
            lcid: 1306,
            rcid: 1306,
            mid: 17,
            value: -6.9913,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "およそ",
            ruby: "オソヨ",
            lcid: 1282,
            rcid: 1282,
            mid: 387,
            value: -9.3486,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "いずれ",
            ruby: "イスレ",
            lcid: 1306,
            rcid: 1306,
            mid: 468,
            value: -8.0760,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "さまざまな",
            ruby: "ザマザマナ",
            lcid: 1287,
            rcid: 454,
            mid: 17,
            value: -11.1537,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "すべて",
            ruby: "ズベテ",
            lcid: 1314,
            rcid: 1314,
            mid: 468,
            value: -7.6718,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "すれば",
            ruby: "スレハ",
            lcid: 597,
            rcid: 318,
            mid: 17,
            value: -9.3682,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "できず",
            ruby: "デキス",
            lcid: 622,
            rcid: 487,
            mid: 17,
            value: -10.8605,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "なければ",
            ruby: "ナケケレバ",
            lcid: 14,
            rcid: 318,
            mid: 17,
            value: -11.1318,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "できる",
            ruby: "デキキル",
            lcid: 619,
            rcid: 619,
            mid: 481,
            value: -5.5489,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "しかし",
            ruby: "シシカシ",
            lcid: 555,
            rcid: 555,
            mid: 282,
            value: -5.8940,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "あるいは",
            ruby: "アルイイハ",
            lcid: 556,
            rcid: 556,
            mid: 287,
            value: -5.9312,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "において",
            ruby: "ニオイイテ",
            lcid: 189,
            rcid: 189,
            mid: 456,
            value: -4.3011,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "そのまま",
            ruby: "ソノノママ",
            lcid: 1281,
            rcid: 1281,
            mid: 282,
            value: -7.7190,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "なかった",
            ruby: "ナカカッタ",
            lcid: 34,
            rcid: 435,
            mid: 17,
            value: -9.3988,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ファッション",
            ruby: "ファション",
            lcid: 1285,
            rcid: 1285,
            mid: 324,
            value: -11.0740,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ファッション",
            ruby: "ファショn",
            lcid: 1285,
            rcid: 1285,
            mid: 324,
            value: -11.0740,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ショッピング",
            ruby: "ショピング",
            lcid: 1283,
            rcid: 1283,
            mid: 442,
            value: -12.1121,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ヨーロッパ",
            ruby: "ヨーロパ",
            lcid: 1293,
            rcid: 1293,
            mid: 240,
            value: -7.8191,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ヨーロッパ",
            ruby: "ヨ-ロパ",
            lcid: 1293,
            rcid: 1293,
            mid: 240,
            value: -7.8191,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "フィンランド",
            ruby: "フィランド",
            lcid: 1294,
            rcid: 1294,
            mid: 240,
            value: -9.1458,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "グリーンランド",
            ruby: "グリーランド",
            lcid: 1293,
            rcid: 1293,
            mid: 272,
            value: -11.6231,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "グリーンランド",
            ruby: "グリ-ランド",
            lcid: 1293,
            rcid: 1293,
            mid: 272,
            value: -11.6231,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "エンディング",
            ruby: "エンディグ",
            lcid: 1285,
            rcid: 1285,
            mid: 283,
            value: -11.5018,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "エンディング",
            ruby: "エンディンググ",
            lcid: 1285,
            rcid: 1285,
            mid: 283,
            value: -11.5018,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "オープニング",
            ruby: "オープニンググ",
            lcid: 1285,
            rcid: 1285,
            mid: 478,
            value: -11.5673,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "オープニング",
            ruby: "オ-プニンググ",
            lcid: 1285,
            rcid: 1285,
            mid: 478,
            value: -11.5673,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "ライセンス",
            ruby: "ラインセンス",
            lcid: 1285,
            rcid: 1285,
            mid: 431,
            value: -11.6652,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "キャラクター",
            ruby: "キャラクラー",
            lcid: 1285,
            rcid: 1285,
            mid: 322,
            value: -9.6944,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "キャラクター",
            ruby: "キャラクラ-",
            lcid: 1285,
            rcid: 1285,
            mid: 322,
            value: -9.6944,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "アニミズム",
            ruby: "アミニズム",
            lcid: 1285,
            rcid: 1285,
            mid: 88,
            value: -14.7059,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "グアテマラ",
            ruby: "グアマテラ",
            lcid: 1294,
            rcid: 1294,
            mid: 272,
            value: -11.2591,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "スタッフ",
            ruby: "スッタフ",
            lcid: 1285,
            rcid: 1285,
            mid: 451,
            value: -10.0743,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "そんな",
            ruby: "ソンア",
            lcid: 1315,
            rcid: 1315,
            mid: 161,
            value: -7.1627,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "チャンネル",
            ruby: "チャンエル",
            lcid: 1285,
            rcid: 1285,
            mid: 20,
            value: -11.7059,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "こんにちは",
            ruby: "コンイチハ",
            lcid: 3,
            rcid: 3,
            mid: 244,
            value: -8.7867,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "どんな",
            ruby: "ドンア",
            lcid: 1315,
            rcid: 1315,
            mid: 17,
            value: -8.2214,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "とんねるず",
            ruby: "トンエルズ",
            lcid: 1292,
            rcid: 1292,
            mid: 409,
            value: -12.7020,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "いろんな",
            ruby: "イロンア",
            lcid: 1315,
            rcid: 1315,
            mid: 17,
            value: -9.2316,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "あんな",
            ruby: "アンア",
            lcid: 1315,
            rcid: 1315,
            mid: 17,
            value: -10.0573,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "みんな",
            ruby: "ミンア",
            lcid: 1306,
            rcid: 1306,
            mid: 17,
            value: -7.9329,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "おんな",
            ruby: "オンア",
            lcid: 1285,
            rcid: 1285,
            mid: 80,
            value: -14.6928,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "新橋",
            ruby: "シmバシ",
            lcid: 1285,
            rcid: 1285,
            mid: 473,
            value: -14.2267,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "難波",
            ruby: "ナmバ",
            lcid: 1293,
            rcid: 1293,
            mid: 231,
            value: -11.8900,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "散歩",
            ruby: "サmポ",
            lcid: 1283,
            rcid: 1283,
            mid: 290,
            value: -11.2927,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "新聞",
            ruby: "シmブン",
            lcid: 1285,
            rcid: 1285,
            mid: 201,
            value: -11.5337,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "新聞",
            ruby: "シmブn",
            lcid: 1285,
            rcid: 1285,
            mid: 201,
            value: -11.5337,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "天ぷら",
            ruby: "テmプラ",
            lcid: 1285,
            rcid: 1285,
            mid: 75,
            value: -13.6111,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "乾杯",
            ruby: "カmパイ",
            lcid: 1283,
            rcid: 1283,
            mid: 451,
            value: -12.8479,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "先輩",
            ruby: "セmパイ",
            lcid: 1285,
            rcid: 1285,
            mid: 364,
            value: -11.0225,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "鉛筆",
            ruby: "エmピツ",
            lcid: 1285,
            rcid: 1285,
            mid: 270,
            value: -13.4935,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "心配",
            ruby: "シmパイ",
            lcid: 1283,
            rcid: 1283,
            mid: 161,
            value: -10.1884,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "完璧",
            ruby: "カmペキ",
            lcid: 1287,
            rcid: 1287,
            mid: 66,
            value: -10.5583,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "球場",
            ruby: "キュジョウ",
            lcid: 1285,
            rcid: 1285,
            mid: 316,
            value: -12.6180,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "流星",
            ruby: "リュセイ",
            lcid: 1285,
            rcid: 1285,
            mid: 466,
            value: -13.9707,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "周年",
            ruby: "シュネン",
            lcid: 1300,
            rcid: 1300,
            mid: 224,
            value: -11.5250,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "周年",
            ruby: "シュネn",
            lcid: 1300,
            rcid: 1300,
            mid: 224,
            value: -11.5250,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中継",
            ruby: "チュケイ",
            lcid: 1283,
            rcid: 1283,
            mid: 305,
            value: -11.2919,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中高",
            ruby: "チュコウ",
            lcid: 1285,
            rcid: 1285,
            mid: 253,
            value: -14.6616,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中心",
            ruby: "チュシン",
            lcid: 1285,
            rcid: 1285,
            mid: 356,
            value: -9.8368,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中心",
            ruby: "チュシn",
            lcid: 1285,
            rcid: 1285,
            mid: 356,
            value: -9.8368,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "きゅうり",
            ruby: "キュリ",
            lcid: 1285,
            rcid: 1285,
            mid: 75,
            value: -13.7573,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "中国",
            ruby: "チュゴク",
            lcid: 1293,
            rcid: 1293,
            mid: 240,
            value: -7.7351,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "駐車場",
            ruby: "チュシャジョウ",
            lcid: 1293,
            rcid: 1293,
            mid: 414,
            value: -10.1170,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "注意",
            ruby: "チュイ",
            lcid: 1283,
            rcid: 1283,
            mid: 468,
            value: -10.4106,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "宇宙船",
            ruby: "ウチュセン",
            lcid: 1285,
            rcid: 1285,
            mid: 173,
            value: -13.2640,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "宇宙船",
            ruby: "ウチュセn",
            lcid: 1285,
            rcid: 1285,
            mid: 173,
            value: -13.2640,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "休憩",
            ruby: "キュケイ",
            lcid: 1283,
            rcid: 1283,
            mid: 109,
            value: -11.5748,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "救急",
            ruby: "キュキュウ",
            lcid: 1285,
            rcid: 1285,
            mid: 402,
            value: -13.0135,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "休日",
            ruby: "キュジツ",
            lcid: 1314,
            rcid: 1314,
            mid: 380,
            value: -10.3618,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "給料",
            ruby: "キュリョウ",
            lcid: 1285,
            rcid: 1285,
            mid: 474,
            value: -12.0394,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "休息",
            ruby: "キュソク",
            lcid: 1283,
            rcid: 1283,
            mid: 271,
            value: -13.3084,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "九州",
            ruby: "キュシュウ",
            lcid: 1293,
            rcid: 1293,
            mid: 397,
            value: -9.7624,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "救助",
            ruby: "キュジョ",
            lcid: 1283,
            rcid: 1283,
            mid: 320,
            value: -12.3909,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "週末",
            ruby: "シュマツ",
            lcid: 1314,
            rcid: 1314,
            mid: 380,
            value: -10.4535,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "収入",
            ruby: "シュニュウ",
            lcid: 1285,
            rcid: 1285,
            mid: 286,
            value: -11.3963,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "留学",
            ruby: "リュガク",
            lcid: 1283,
            rcid: 1283,
            mid: 314,
            value: -11.4885,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "流行",
            ruby: "リュコウ",
            lcid: 1283,
            rcid: 1283,
            mid: 356,
            value: -11.3985,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "流通",
            ruby: "リュツウ",
            lcid: 1283,
            rcid: 1283,
            mid: 375,
            value: -11.5682,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入学",
            ruby: "ニュガク",
            lcid: 1283,
            rcid: 1283,
            mid: 364,
            value: -10.7441,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入院",
            ruby: "ニュイン",
            lcid: 1283,
            rcid: 1283,
            mid: 46,
            value: -11.2958,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入院",
            ruby: "ニュイn",
            lcid: 1283,
            rcid: 1283,
            mid: 46,
            value: -11.2958,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "入力",
            ruby: "ニュリョク",
            lcid: 1283,
            rcid: 1283,
            mid: 45,
            value: -11.0969,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "連用形",
            ruby: "レニョウケイ",
            lcid: 1285,
            rcid: 1285,
            mid: 327,
            value: -15.7467,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "日本郵便",
            ruby: "ニホニュウビン",
            lcid: 1288,
            rcid: 1288,
            mid: 118,
            value: -14.6246,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "日本郵便",
            ruby: "ニホニュウビn",
            lcid: 1288,
            rcid: 1288,
            mid: 118,
            value: -14.6246,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用",
            ruby: "セニョウ",
            lcid: 1283,
            rcid: 1283,
            mid: 319,
            value: -10.5847,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "金曜日",
            ruby: "キニョウビ",
            lcid: 1314,
            rcid: 1314,
            mid: 380,
            value: -10.7188,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "全容",
            ruby: "ゼニョウ",
            lcid: 1285,
            rcid: 1285,
            mid: 468,
            value: -15.1059,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "転用",
            ruby: "テニョウ",
            lcid: 1283,
            rcid: 1283,
            mid: 375,
            value: -12.2293,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用車",
            ruby: "セニョウシャ",
            lcid: 1283,
            rcid: 1298,
            mid: 17,
            value: -15.0410,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用線",
            ruby: "セニョウセン",
            lcid: 1288,
            rcid: 1288,
            mid: 280,
            value: -13.5495,
            metadata: .isKeyboardTypoCorrection
        ),
        DicdataElement(
            word: "専用線",
            ruby: "セニョウセn",
            lcid: 1288,
            rcid: 1288,
            mid: 280,
            value: -13.5495,
            metadata: .isKeyboardTypoCorrection
        ),
    ]
}

func makeConversionDictionaryEntries(
    userEntries: [DicdataElement],
    experimentalTypoCorrectionEnabled: Bool
) -> [DicdataElement] {
    guard experimentalTypoCorrectionEnabled else {
        return userEntries
    }
    return userEntries + makeKeyboardTypoDictionaryEntries()
}

private func keyboardTypoDictionaryEntryKey(ruby: String, word: String) -> String {
    ruby + "\u{0}" + word
}

private let keyboardTypoDictionaryEntryKeys = Set(
    makeKeyboardTypoDictionaryEntries().map {
        keyboardTypoDictionaryEntryKey(ruby: $0.ruby, word: $0.word)
    }
)

func keyboardTypoDictionaryEntry(in candidate: Candidate) -> DicdataElement? {
    candidate.data.first {
        keyboardTypoDictionaryEntryKeys.contains(
            keyboardTypoDictionaryEntryKey(ruby: $0.ruby, word: $0.word)
        )
    }
}

func disableLearningForKeyboardTypoDictionaryCandidates(
    _ candidates: [Candidate],
    experimentalTypoCorrectionEnabled: Bool
) -> [Candidate] {
    guard experimentalTypoCorrectionEnabled else {
        return candidates
    }
    return candidates.map { source in
        var candidate = source
        if keyboardTypoDictionaryEntry(in: candidate) != nil {
            candidate.isLearningTarget = false
        }
        return candidate
    }
}
